Server/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('musices.urls', namespace="musices")),
    path('genre/', include('genres.urls', namespace="genres")),
    path('albume/', include('alboms.urls', namespace="albomes")),
    path('auth/', include('authentication.urls', namespace="authentication")),
    path('profile/', include('profiles.urls', namespace="profile")),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('subscription/', include('subscription.urls', namespace="subscription")),
    path('home/', include('home.urls', namespace="home")),
    path('', include('landing.urls', namespace="landing")),
    path('search/', include('search.urls', namespace="search")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('events/', include('events.urls', namespace="events")),
    
    # PWA url
    path('', include('pwa.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alboms/urls.py
from django.urls import path
from . import views


app_name = "alboms"


urlpatterns = [
    path("list/", views.AlbomesList.as_view(), name="albomes_list"),
    path("<slug:slug>/", views.AlbomDetail.as_view(), name="albome_detail"),
    path('add-comment/<slug:slug>/<int:pk>/', views.AddCommentView.as_view(), name="add_comment"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.AddReplyView.as_view(), name="add_reply"),
]

authentication/urls.py
from django.urls import path
from . import views


app_name = "authentication"


urlpatterns = [
    path('login/', views.Login.as_view(), name="login"),
    path('logout/', views.Logout.as_view(), name="logout"),
    path('register/', views.Register.as_view(), name="register"),
    path('chek-otp/', views.CheckOtp.as_view(), name="check_otp"),
    
    # change password
    path('reset-password/', views.ResetPassword.as_view(), name="reset_password"),
    path('validate-reset-password-otp/', views.ValidatePasswordOtp.as_view(), name="validate_otp"),
    path('chnage-password/', views.ChangePassword.as_view(), name="change_password"),
]

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('', views.EventsList.as_view(), name="events_list"),
    path('detail/<slug:slug>/', views.EventDetail.as_view(), name="event_detail")
]

genres/urls.py
from django.urls import path
from . import views


app_name = "genres"


urlpatterns = [
    # Genre Url
    path('list/', views.GenresView.as_view(), name="genres"),
    path('<slug:slug>/', views.GenreDetail.as_view(), name="genre_detail"),
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path('', views.Home.as_view(), name="home")
]

musices/urls.py
from django.urls import path
from . import views


app_name = "musices"


urlpatterns = [
    # Musices urls
    path('list/', views.MusicesView.as_view(), name="musices_list"),
    path('<slug:slug>/', views.MusicDetail.as_view(), name="music_detail"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.MusicCommentReply.as_view(), name="music_comment_reply"),
]

authentication/models.py
from django.db import models
from django.core import validators




class Otp(models.Model):
    
    email = models.EmailField(
        max_length=255,
        verbose_name="ایمیل",
        validators=[
            validators.EmailValidator
        ]
    )
    
    username = models.CharField(
        max_length=255,
        verbose_name="نام کاربری"
    )
    
    password = models.CharField(
        max_length=255,
        verbose_name="رمز عبور"
    )
    
    otp_code = models.IntegerField(
        verbose_name="کد otp"
    )
    
    token = models.CharField(
        verbose_name="توکن",
        max_length=100,
        unique=True
    )

    
    class Meta:
        verbose_name = "کد اعتبارسنجی"
        verbose_name_plural = "کدهای اعتبارسنجی"
        
        
    def __str__(self):
        return f'{self.id}---{self.email}---{self.otp_code}'
    

class ResetPasswordOtp(models.Model):
    
    otp_code = models.IntegerField(
        verbose_name="کد otp"
    )
    
    token = models.CharField(
        verbose_name="توکن",
        max_length=100,
        unique=True
    )
    
    email = models.EmailField(
        max_length=255,
        verbose_name="ایمیل",
        validators=[
            validators.EmailValidator
        ]
    )
    
    class Meta:
        verbose_name = "کد اعتبار سنجی رمزعبور"
        verbose_name_plural = "کد های اعتبار سنجی رمزعبور"
        
    
    def __str__(self):
        return f'{self.token}----{self.otp_code}'

authentication/forms.py
from django import forms


class LoginForm(forms.Form):
    
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'email',
                'type' : 'text'
            }
        )
    )
    
    password = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'password',
                'type' : 'password'
            }
        )
    )


class RegistrationForm(forms.Form):
    
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'email',
                'type' : 'text'
            }
        )
    )
    
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'username',
                'type' : 'text'
            }
        )
    )
    
    password = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'password',
                'type' : 'password'
            }
        )
    )
    
    password_conf = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'password',
                'type' : 'password'
            }
        )
    )
    
class OtpForm(forms.Form):
    
    otp = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'otp',
                'type' : 'text'
            }
        )
    )
    
class CahngePasswordForm(forms.Form):
    
    password = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'password',
                'type' : 'text'
            }
        )
    )
    
    password_conf = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class' : 'form-control',
                'id' : 'password',
                'type' : 'text'
            }
        )
    )

authentication/views.py
<<<<<<< HEAD
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout, login, authenticate
from django.utils.crypto import get_random_string
from django.core.mail import send_mail
from django.urls import reverse
from django.views import View

from users.models import User

from .forms import LoginForm, RegistrationForm, OtpForm, CahngePasswordForm
from .models import Otp, ResetPasswordOtp

from random import randint



class Logout(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == True:
                
            logout(request)
            
            return redirect('/')
        else:
            return redirect('home:home')



class Login(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == False:
            
            form = LoginForm()

            return render(
                request, 'authentication/login.html', {
                    'form' : form
                }
            )
        else:
            return redirect('home:home')
        
        
    
    def post(self, request):
        
        if request.user.is_authenticated == False:

            form = LoginForm(request.POST)
    
            if form.is_valid():
                
                cd = form.cleaned_data
                
                user = authenticate(
                    username=cd['email'],
                    password=cd['password']
                )
                
                if user is not None:
                    
                    login(request, user)
                    
                    return redirect('home:home')
                else:
                    form.add_error('email', 'ایمیل یا رمزعبور معتبر نیست!')
            else:
                form.add_error('email', 'ایمیل یا رمزعبور معتبر نیست!')
        else:
            return redirect('home:home')
        return render(
            request, 'authentication/login.html', {
                'form' : form
            }
        )



class Register(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == False:
            
            form = RegistrationForm()
            
            return render(
                request, 'authentication/register.html', {
                    'form' : form
                }
            )
        else:
            return redirect('home:home')
        
    
    def post(self, request):
         
        if request.user.is_authenticated == False:
            
            form = RegistrationForm(request.POST)
            
            if form.is_valid():
                
                cd = form.cleaned_data
                
                if cd['password'] == cd['password_conf']:
                    
                    if len(cd['password_conf']) <= 8 and len(cd['password_conf']) >= 8:
                        
                        user_username_validation = User.objects.filter(username=cd['username']).exists()
                        
                        if user_username_validation == False:
                            
                            user_email_validation = User.objects.filter(email=cd['email']).exists()
                            
                            if user_email_validation == False:
                                
                                otp_code = randint(100000, 999999)
                                
                                token = get_random_string(100)
                                
                                otp = Otp.objects.create(
                                    email = cd['email'],
                                    username = cd['username'],
                                    password = cd['password'],
                                    otp_code = otp_code,
                                    token = token
                                )
                                
                                send_mail(
                                    subject = 'Hip Hop Tweety veryfication',
                                    message = f'به Hip Hop Tweety خوش آمدید. برای تایید ایمیل خودتون کد: {otp_code} را وارد کنید',
                                    from_email = 'email@hip-hop-tweety.com',
                                    recipient_list = [cd['email']],
                                    fail_silently = False,
                                )
                                
                                return redirect(reverse('authentication:check_otp') + f'?token={token}')
                            else:
                                form.add_error('email', 'این ایمیل قبلا ثبت شده است!')
                        else:
                            form.add_error('username', 'این نام کاربری از قبل وجود دارد!')
                    else:
                        form.add_error('password', 'اندازه رمزعبور باید بین 8 تا 16 کاراکتر باشد!')
                else:
                    form.add_error('password', 'پسورد های وارد شده باهم برابر نیستند!')
            else:
                form.add_error('email', 'اطلاعات وارد شده معتبر نیستند!')
        else:
            return redirect('home:home')
        return render(
                request, 'authentication/register.html', {
                    'form' : form
                }
            )
        
        
class CheckOtp(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == False:
            
            form = OtpForm()
        
            return render(
                request, 'authentication/check_otp.html', {
                    'form' : form
                }
            )
        else:
            return redirect('home:home')
        
    
    def post(self, request):
        
        if request.user.is_authenticated == False:
            
            form = OtpForm(request.POST)

            token = request.GET.get('token')
            
            otp = get_object_or_404(
                Otp, token = token
            )
            
            if form.is_valid():
                
                cd = form.cleaned_data
                
                if int(cd['otp']) == int(otp.otp_code):
                    
                    user = User.objects.create_user(
                        username = otp.username,
                        password = otp.password,
                        email = otp.email,
                    )
                    
                    user.save()
                    
                    otp.delete()
                    
                    login(request, user)
                    
                    return redirect('home:home')
                else:
                    form.add_error('otp', 'کد وارد شده معتبر نیست!')
            else:
                form.add_error('otp', 'کد وارد شده معتبر نیست!')
        else:
            return redirect('homehome:homehome')
        return render(
            request, 'authentication/check_otp.html', {
                'form' : form,
            }
        )
        
        

class ResetPassword(View):
    
    def get(self, request):
        
        return render(
            request, 'authentication/reset_password.html', {
                
            }
        )
        
    
    def post(self, request):
        
        email = request.POST.get('email')
        
        user_email_validation = User.objects.filter(email=email).exists()
        
        if user_email_validation == True:
        
            code = randint(100000, 999999)
            
            token = get_random_string(100)
            
            
            otp = ResetPasswordOtp.objects.create(
                email = email,
                otp_code = code,
                token = token
            )
            otp.save()
            
            send_mail(
                subject = 'Hip Hop Tweety ریست کردن رمزعبور',
                message = f'به Hip Hop Tweety خوش آمدید. برای تایید ایمیل خودتون کد: {code} را وارد کنید',
                from_email = 'email@hip-hop-tweety.com',
                recipient_list = [email],
                fail_silently = False,
            )
            
            return redirect(reverse('authentication:validate_otp')+ f'?token={token}')
        else:
            return redirect('authentication:reset_password')
        return render(
            request, 'authentication/reset_password.html', {
                
            }
        )

        

class ValidatePasswordOtp(View):
    
    def get(self, request):
        
        token = request.GET.get('token')
        
        try:
            otp = ResetPasswordOtp.objects.get(token=token)
            
            return render(
                request, 'authentication/validate_otp.html', {
                    
                }
            )
        except otp.DoesNotExist:
            return redirect('authentication:reset_password')
        
    
    def post(self, request):
        
        token = request.GET.get('token')
        
        try:
            otp = ResetPasswordOtp.objects.get(token=token)
            
            code = request.POST.get('code')
            
            if int(code) == int(otp.otp_code):
                return redirect(reverse('authentication:change_password')+ f'?token={token}')
            else:
                return redirect('authentication:reset_password')
        except otp.DoesNotExist:
            return redirect('authentication:reset_password')

class ChangePassword(View):
    
    def get(self, request):
        
        form = CahngePasswordForm()
        
        return render(
            request, 'authentication/change_password.html', {
                'form' : form
            }
        )
        
    def post(self, request):
        
        form = CahngePasswordForm(request.POST)
        
        token = request.GET.get('token')
        
        password_otp = get_object_or_404(

authentication/templates/authentication/check_otp.html
<<<<<<< HEAD
{% extends "base.html" %}
{% load static %}


{% block title %}تایید کد احراز حویتی | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
          href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}

{% block main %}
<div class="auth py-5">
  <div class="container">
    <div class="row">
      <div class="col-xl-5 col-lg-7 col-md-9 col-sm-11 mx-auto">
        <div class="card">
          <div class="card-body p-sm-5">
            <h4> تایید کد اعتبارسنجی<span class="text-primary">Hip Hop Tweety</span></h4>
            <p class="fs-6">
              
            </p>
            <form method="post" class="mt-5">
              {% csrf_token %}
              <div class="mb-3">
                <label for="otp" class="form-label fw-medium"
                  >کد اعتبارسنجی</label
                >
                <p class="link-primary fw-medium" style="text-color : red;">
                  {{ form.otp.errors }}
                </p>
                {{ form.otp }}
              </div>
              <p>
                کد را دریافت نکرده اید؟<br /><a
                    href="{% url "authentication:register" %}"
                    class="fw-medium external"
                    >امتحان مجدد</a
                >
              </p>
              <div class="mb-5">
                <input
                  type="submit"
                  class="btn btn-primary w-100"
                  value="تایید"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
=======
{% extends "base.html" %}
{% load static %}


{% block title %}تایید کد احراز حویتی | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
          href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}

{% block main %}
<div class="auth py-5">
  <div class="container">
    <div class="row">
      <div class="col-xl-5 col-lg-7 col-md-9 col-sm-11 mx-auto">
        <div class="card">
          <div class="card-body p-sm-5">
            <h4> تایید کد اعتبارسنجی<span class="text-primary">Hip Hop Tweety</span></h4>
            <p class="fs-6">
              
            </p>
            <form method="post" class="mt-5">
              {% csrf_token %}
              <div class="mb-3">
                <label for="otp" class="form-label fw-medium"
                  >کد اعتبارسنجی</label
                >
                <p class="link-primary fw-medium" style="text-color : red;">
                  {{ form.otp.errors }}
                </p>
                {{ form.otp }}
              </div>
              <p>
                کد را دریافت نکرده اید؟<br /><a
                    href="{% url "authentication:register" %}"
                    class="fw-medium external"
                    >امتحان مجدد</a
                >
              </p>
              <div class="mb-5">
                <input
                  type="submit"
                  class="btn btn-primary w-100"
                  value="تایید"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
>>>>>>> 9000df78aa17a8af2d9e5820cd25dc60c285d9ef
{% endblock main %}

authentication/templates/authentication/validate_otp.html
{% extends "base.html" %}
{% load static %}


{% block title %}تایید کد بازیابی رمز عبور | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}

{% block main %}
<div class="auth py-5">
  <div class="container">
    <div class="row">
      <div class="col-xl-5 col-lg-7 col-md-9 col-sm-11 mx-auto">
        <div class="card">
          <div class="card-body p-sm-5">
            <h4>تایید کد بازیابی رمز عبور<span class="text-primary">Hip Hop Tweety</span></h4>
            <p class="fs-6">
              
            </p>
            <form action="" method="post" class="mt-5">
              {% csrf_token %}
              <div class="mb-3">
                <label for="code" class="form-label fw-medium">کد</label>
                <input type="text" id="code" class="form-control"  name="code"/>
              </div>
              <p>
                کد را دریافت نکرده اید؟<br /><a
                    href="{% url "authentication:reset_password" %}"
                    class="fw-medium external"
                    >امتحان مجدد</a
                >
              </p>
              <div class="mb-5">
                <input
                  type="submit"
                  class="btn btn-primary w-100"
                  value="تایید"
                />
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock main %}