Server/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('musices.urls', namespace="musices")),
    path('genre/', include('genres.urls', namespace="genres")),
    path('albume/', include('alboms.urls', namespace="albomes")),
    path('auth/', include('authentication.urls', namespace="authentication")),
    path('profile/', include('profiles.urls', namespace="profile")),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('subscription/', include('subscription.urls', namespace="subscription")),
    path('home/', include('home.urls', namespace="home")),
    path('', include('landing.urls', namespace="landing")),
    path('search/', include('search.urls', namespace="search")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('events/', include('events.urls', namespace="events")),
    
    # PWA url
    path('', include('pwa.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alboms/urls.py
from django.urls import path
from . import views


app_name = "alboms"


urlpatterns = [
    path("list/", views.AlbomesList.as_view(), name="albomes_list"),
    path("<slug:slug>/", views.AlbomDetail.as_view(), name="albome_detail"),
    path('add-comment/<slug:slug>/<int:pk>/', views.AddCommentView.as_view(), name="add_comment"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.AddReplyView.as_view(), name="add_reply"),
]

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('', views.EventsList.as_view(), name="events_list"),
    path('detail/<slug:slug>/', views.EventDetail.as_view(), name="event_detail")
]

genres/urls.py
from django.urls import path
from . import views


app_name = "genres"


urlpatterns = [
    # Genre Url
    path('list/', views.GenresView.as_view(), name="genres"),
    path('<slug:slug>/', views.GenreDetail.as_view(), name="genre_detail"),
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path('', views.Home.as_view(), name="home")
]

musices/urls.py
from django.urls import path
from . import views


app_name = "musices"


urlpatterns = [
    # Musices urls
    path('list/', views.MusicesView.as_view(), name="musices_list"),
    path('<slug:slug>/', views.MusicDetail.as_view(), name="music_detail"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.MusicCommentReply.as_view(), name="music_comment_reply"),
]

subscription/urls.py
from django.urls import path
from . import views


app_name = "subscription"

urlpatterns = [
    path("plans/", views.SubscriptionPlansView.as_view(), name="plans")
]

subscription/models.py
from django.db import models
# from users.models import User
from django.utils import timezone



class SubscriptionPlan(models.Model):
    
    name = models.CharField(
        verbose_name="عنوان پلن اشتراک",
        max_length=200,
    )
    
    price_pre_month = models.IntegerField(
        verbose_name="قیمت پلن اشتراک برای هر ماه"
    )
    
    is_active = models.BooleanField(
        verbose_name="وضعیت پلن اشتراک",
        default=True,
    )
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['created']
        verbose_name = "پلن اشتراک"
        verbose_name_plural = "پلن های اشتراک"
        
    
    def __str__(self):
        return f'{self.name} price for month : {self.price_pre_month}'



class UserSubscription(models.Model):
    
    user = models.ForeignKey(
        'users.User',
        on_delete=models.CASCADE,
        related_name="user_sub",
        verbose_name="کاربر",
    )
    
    start_date = models.DateTimeField(
        verbose_name="تاریخ شروع اشتراک"
    )
    
    end_date = models.DateTimeField(
        verbose_name="تاریخ اتمام اشتراک"
    )
    
    is_active = models.BooleanField(
        verbose_name="وضعیت اشتراک",
        default=False
    )
    
    plan = models.ForeignKey(
        SubscriptionPlan,
        on_delete=models.SET_NULL,
        related_name="plans",
        verbose_name="پلن",
        null=True
    )
    
    
    class Meta:
        verbose_name = "اشتراک کاربر"
        verbose_name_plural = "اشتراک کاربران"
        
    def __str__(self):
        return f"{self.user.username} - {self.start_date} - {self.end_date} - {self.is_active}"
    
    def validate_subscription(self):
        if self.end_date < timezone.now():
            self.is_active = False
            self.save()
            return False
        else:
            self.is_active = True
            self.save()
            return True
        
    def validated_day(self):
        if self.end_date < timezone.now():
            return 0
        else:
            return (self.end_date - timezone.now()).days

subscription/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse
from django.views import View
from .models import UserSubscription, SubscriptionPlan
from users.models import User



class SubscriptionPlansView(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == True:
            
            plans = SubscriptionPlan.objects.all()
            
            try:
                user_subscription = UserSubscription.objects.get(user=request.user)
                
                return render(
                    request, 'subscription/subscription_plans.html', {
                        'plans' : plans,
                        'user_subscription' : user_subscription
                    }
                )
            except:
                return render(
                    request, 'subscription/subscription_plans.html', {
                        'plans' : plans,
                    }
                )
        else:
            return redirect('authentication:login')

subscription/templates/subscription/subscription_plans.html
{% extends "base.html" %}
{% load static %}

{% block title %}طرح های اشتراک | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center active"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}


{% block main %}
    <div class="hero"></div>
    <div class="under-hero container">
      <div class="section">
        <div class="plan bg-light">
          <div class="card plan__info overflow-hidden">
            <div class="card-body d-flex flex-column p-0">
              <div class="p-4">
                <h4 class="mb-3">
                  اشتراک <span class="text-primary">شما</span>
                </h4>
                <p class="fs-6">
                  طرح اشتراک <b> </b> شما ظرف {{ user_subscription.validated_day }} روز پایان می‌یابد،
                  لطفاً طرح خود را انتخاب کنید.
                </p>
              </div>
              <div class="px-3 text-center mt-auto">
                <img src="images/misc/plan.png" class="img-fluid" alt="" />
              </div>
            </div>
          </div>
          <div class="plan__data">
            {% for plan in plans %}
              <div class="card plan__col">
                <div class="card-body fw-medium">
                  <div class="d-flex align-items-center text-dark mb-4">
                    <i class="ri-music-2-line fs-3"></i>
                    <h4 class="mb-0 ps-3">
                      اشتراک <span class="text-primary">{{ plan.name }}</span>
                    </h4>
                  </div>
                  <p class="fs-6 opacity-50">شامل چه چیزی میباشد</p>
                  <div class="d-flex mb-3">
                    <i
                      class="ri-checkbox-circle-fill text-primary opacity-75 fs-6"
                    ></i>
                    <span class="ps-2">دسترسی به تمام موزیک ها</span>
                  </div>
                  <div class="d-flex mb-3">
                    <i
                      class="ri-checkbox-circle-fill text-primary opacity-75 fs-6"
                    ></i>
                    <span class="ps-2">بدون تبلیغات</span>
                  </div>
                </div>
                <div class="card-footer pb-4 pb-sm-0">
                  <div class="text-dark mb-3">
                    <span class="fs-4 fw-bold">{{ plan.price_pre_month }} هزار تومان</span>/ماهانه
                  </div>
                  <a href="{% url "payment:time_selection" plan.name %}" class="btn btn-primary w-100">
                    انتخاب
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
{% endblock main %}