Server/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('musices.urls', namespace="musices")),
    path('genre/', include('genres.urls', namespace="genres")),
    path('albume/', include('alboms.urls', namespace="albomes")),
    path('auth/', include('authentication.urls', namespace="authentication")),
    path('profile/', include('profiles.urls', namespace="profile")),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('subscription/', include('subscription.urls', namespace="subscription")),
    path('home/', include('home.urls', namespace="home")),
    path('', include('landing.urls', namespace="landing")),
    path('search/', include('search.urls', namespace="search")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('events/', include('events.urls', namespace="events")),
    
    # PWA url
    path('', include('pwa.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alboms/urls.py
from django.urls import path
from . import views


app_name = "alboms"


urlpatterns = [
    path("list/", views.AlbomesList.as_view(), name="albomes_list"),
    path("<slug:slug>/", views.AlbomDetail.as_view(), name="albome_detail"),
    path('add-comment/<slug:slug>/<int:pk>/', views.AddCommentView.as_view(), name="add_comment"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.AddReplyView.as_view(), name="add_reply"),
]

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('', views.EventsList.as_view(), name="events_list"),
    path('detail/<slug:slug>/', views.EventDetail.as_view(), name="event_detail")
]

favorites/urls.py
from django.urls import path
from . import views


app_name = "favorite"


urlpatterns = [
    # Favorites page url
    path('', views.UserFavoritesView.as_view(), name="favorites"),
    # Music favorite (add&remove) url
    path('music-favorite/<slug:slug>/', views.UserMusicFavoriteView.as_view(), name="user_music_faver"),
    # Albume favorite (add&remove) url
    path('albume-favorite/<slug:slug>/', views.UserAlbumeFavoriteView.as_view(), name="user_albume_faver"),
]

genres/urls.py
from django.urls import path
from . import views


app_name = "genres"


urlpatterns = [
    # Genre Url
    path('list/', views.GenresView.as_view(), name="genres"),
    path('<slug:slug>/', views.GenreDetail.as_view(), name="genre_detail"),
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path('', views.Home.as_view(), name="home")
]

musices/urls.py
from django.urls import path
from . import views


app_name = "musices"


urlpatterns = [
    # Musices urls
    path('list/', views.MusicesView.as_view(), name="musices_list"),
    path('<slug:slug>/', views.MusicDetail.as_view(), name="music_detail"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.MusicCommentReply.as_view(), name="music_comment_reply"),
]

genres/models.py
from django.db import models
from django.urls import reverse

class Genre(models.Model):
    
    genre = models.CharField(
        verbose_name= "ژانر",
        max_length=200,
        unique=True
    )
    
    slug = models.SlugField(
        verbose_name= "اسلاگ",
        max_length=200,
        unique=True
    )
    
    image = models.ImageField(
        upload_to="Genres/images/",
        verbose_name="تصویر"
    )
    
    class Meta:
        ordering = ['genre']
        verbose_name = "ژانر"
        verbose_name_plural = "ژانر ها"

    
    def __str__(self):
        return self.genre
    
    
    def get_absolute_url(self):
        return reverse("genres:genre_detail", kwargs={"slug": self.slug})
    

genres/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views import View
from .models import Genre
from musices.models import Music
from subscription.models import UserSubscription

class GenresView(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == True:
            try:
                user_sub = UserSubscription.objects.get(user=request.user)
                
                user_sub.validate_subscription()
                
                if user_sub.is_active == True:
                    
                    genres = Genre.objects.all()
        
                    return render(
                        request, 'genres/list.html', {
                            'genres' : genres
                        }
                    )
                else:
                    return redirect('subscription:plans')
            except:
                return redirect('subscription:plans')
        else:
            return redirect('authentication:login')
        
        



class GenreDetail(View):
    
    def get(self, request, slug):
        
        if request.user.is_authenticated == True:
            try:
                user_sub = UserSubscription.objects.get(user=request.user)
                
                user_sub.validate_subscription()
                
                if user_sub.is_active == True:
                    
                    genre = get_object_or_404(Genre, slug=slug)
                    
                    queryset = Music.objects.filter(genre=genre).order_by('-likes')
                    
                    genres = Genre.objects.all().order_by('?')
                    
                    page_number = request.GET.get('page')
                    paginator = Paginator(queryset, 15)
                    queryset = paginator.get_page(page_number)
                    
                    return render(
                        request, 'genres/detail.html', {
                            'genre' : genre,
                            'genres' : genres,
                            'genere_musices' : queryset
                        }
                    )
                else:
                    return redirect('subscription:plans')
            except:
                return redirect('subscription:plans')
        else:
            return redirect('authentication:login')

genres/templates/genres/detail.html
{% extends "base.html" %}
{% load static %}
{% load faver_validator %}

{% block title %}{{ genre.genre }} سبک | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}


{% block main %}
    <div class="hero"></div>
    <div class="under-hero container">
        <div class="list">
            <div class="row">
              <div class="col-xl-12">  
              {% comment %} Musices list started {% endcomment %}
                {% for music in genere_musices %}
                  <div
                  class="list__item"
                  data-song-id="{{ music.id }}"
                  data-song-name="{{ music.title }}"
                  data-song-artist="{{ music.artist }}"
                  data-song-album="{{ music.title }}"
                  data-song-url="{{ music.music_file.url }}"
                  data-song-cover="{{ music.image.url }}"
                  >
                    <div class="list__cover">
                        <img src="{{ music.image.url }}" alt="{{ music.image.url }}" />
                        <a href="javascript:void(0);" class="btn btn-play btn-sm btn-default btn-icon rounded-pill" data-play-id="{{ music.id }}" aria-label="Play pause">
                            <i class="ri-play-fill icon-play"></i>
                            <i class="ri-pause-fill icon-pause"></i>
                        </a>
                    </div>
                    <div class="list__content">
                        <a href="{{ music.get_absolute_url }}" class="list__title text-truncate">
                            {{ music.title }}
                        </a>
                        <p class="list__subtitle text-truncate">
                            {{ music.artist }}
                        </p>
                    </div>
                    <ul class="list__option">
                      {% faver_validator user_id=user.id music_id=music.id as is_faver %}
                      {% if is_faver %}
                        <li>
                          <a
                            href="{% url "favorites:user_music_faver" music.slug %}?next=/genre/{{genre.slug}}/"
                            class="d-inline-flex active"
                            data-favorite-id="{{  music.id }}"
                            ><i class="ri-heart-line heart-empty"></i>
                            <i class="ri-heart-fill heart-fill"></i>
                          </a>
                        </li>
                      {% else %}
                        <li>
                            <a
                            href="{% url "favorites:user_music_faver" music.slug %}?next=/genre/{{genre.slug}}/"
                            class="d-inline-flex"
                            data-favorite-id="{{ music.id }}"
                            >
                                <i class="ri-heart-line heart-empty"></i>
                                <i class="ri-heart-fill heart-fill"></i>
                            </a>
                        </li>
                      {% endif %}
                        <li>{{ music.music_time }}</li>
                        <li class="dropstart d-inline-flex">
                            <a
                            class="dropdown-link"
                            href="javascript:void(0);"
                            role="button"
                            data-bs-toggle="dropdown"
                            aria-label="Cover options"
                            aria-expanded="false"
                            ><i class="ri-more-fill"></i
                            ></a>
                            <ul class="dropdown-menu dropdown-menu-sm">
                              <li>
                                  <a
                                  class="dropdown-item"
                                  href="javascript:void(0);"
                                  role="button"
                                  data-queue-id="{{ music.id }}"
                                  >افزودن به لیست</a
                                  >
                              </li>
                              <li>
                                  <a
                                  class="dropdown-item"
                                  href="javascript:void(0);"
                                  role="button"
                                  data-next-id="{{ music.id }}"
                                  >بعدی برای پخش</a
                                  >
                              </li>
                              <li>
                                  <a
                                  class="dropdown-item"
                                  href="javascript:void(0);"
                                  role="button"
                                  >اشتراک</a
                                  >
                              </li>
                              <li class="dropdown-divider"></li>
                              <li>
                                  <a
                                  class="dropdown-item"
                                  href="javascript:void(0);"
                                  role="button"
                                  data-play-id="{{ music.id }}"
                                  >پخش</a
                                  >
                              </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                {% endfor %}
              {% comment %} Musices list ended {% endcomment %}
              <br>
              {% if genere_musices.has_other_pages %}
                <div class="mt-5 text-center">
                  {% if genere_musices.has_previous %}
                    <a href="/genre/{{ genre.slug }}/?page={{ genere_musices.previous_page_number }}" class="btn btn-primary">
                      <div class="btn__wrap">
                        <span>قبلی</span>
                        <i class="ri-arrow-left-line fs-6"></i>
                      </div>
                    </a>
                  {% endif %}
                  {% if genere_musices.has_next %}
                    <a href="/genre/{{ genre.slug }}/?page={{ genere_musices.next_page_number }}" class="btn btn-primary"
                      ><div class="btn__wrap">
                        <i class="ri-arrow-right-line fs-6"></i> <span>بعدی</span>
                      </div></a
                    >
                  {% endif %}
                </div>
              {% endif %}
              </div>
            </div>
          </div>
      <div class="section">
        <div class="section__head">
          <h3 class="mb-0">
            جست و جوی <span class="text-primary">ژانر ها</span>
          </h3>
        </div>
        <div class="swiper-carousel">
          <div
            class="swiper"
            dir="rtl"
            class="swiper"
            data-swiper-slides="4"
            data-swiper-autoplay="true"
          >
            <div class="swiper-wrapper">
                {% for genre in genres %}
                    <div class="swiper-slide">
                        <div class="cover cover--round">
                        <a href="{{ genere.get_absolute_url }}" class="cover__image"
                            ><img
                            src="{{ genre.image.url }}"
                            alt="{{ genre.genre }}"
                            />
                            <div class="cover__image__content">
                            <span class="cover__title mb-1 fs-6 text-truncate"
                                >{{ genre.genre }}</span
                            >
                            </div>
                        </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
          </div>
          <div class="swiper-button-prev btn-default rounded-pill"></div>
          <div class="swiper-button-next btn-default rounded-pill"></div>
        </div>
      </div>
    </div>
{% endblock main %}

genres/templates/genres/list.html
{% extends "base.html" %}
{% load static %}


{% block title %}سبک ها | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center active"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}


{% block main %}
    <div class="hero"></div>
    <div class="under-hero container">
      <div class="section">
        <div class="section__head">
          <h3 class="mb-0">
            ژانر های <span class="text-primary">موزیک</span>
          </h3>
        </div>
        <div class="row g-4">
          {% for genre in genres %}
            <div class="col-xl-3 col-sm-6">
                <div class="cover cover--round">
                    <a href="{{ genre.get_absolute_url }}" class="cover__image"
                        ><img
                        src="{{ genre.image.url }}"
                        alt="{{ genre.genre }}"
                        />
                        <div class="cover__image__content">
                        <span class="cover__title mb-1 fs-6 text-truncate">
                            {{ genre.genre }}
                        </span>
                        </div>
                    </a>
                </div>
            </div>
          {% endfor %}
        </div>
        <div class="swiper-button-prev btn-default rounded-pill"></div>
        <div class="swiper-button-next btn-default rounded-pill"></div>
      </div>
      </div>
    </div>
{% endblock main %}