Server/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('musices.urls', namespace="musices")),
    path('genre/', include('genres.urls', namespace="genres")),
    path('albume/', include('alboms.urls', namespace="albomes")),
    path('auth/', include('authentication.urls', namespace="authentication")),
    path('profile/', include('profiles.urls', namespace="profile")),
    path('favorites/', include('favorites.urls', namespace="favorites")),
    path('subscription/', include('subscription.urls', namespace="subscription")),
    path('home/', include('home.urls', namespace="home")),
    path('', include('landing.urls', namespace="landing")),
    path('search/', include('search.urls', namespace="search")),
    path('payment/', include('payment.urls', namespace="payment")),
    path('events/', include('events.urls', namespace="events")),
    
    # PWA url
    path('', include('pwa.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alboms/urls.py
from django.urls import path
from . import views


app_name = "alboms"


urlpatterns = [
    path("list/", views.AlbomesList.as_view(), name="albomes_list"),
    path("<slug:slug>/", views.AlbomDetail.as_view(), name="albome_detail"),
    path('add-comment/<slug:slug>/<int:pk>/', views.AddCommentView.as_view(), name="add_comment"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.AddReplyView.as_view(), name="add_reply"),
]

events/urls.py
from django.urls import path
from . import views


app_name = "events"

urlpatterns = [
    path('', views.EventsList.as_view(), name="events_list"),
    path('detail/<slug:slug>/', views.EventDetail.as_view(), name="event_detail")
]

favorites/urls.py
from django.urls import path
from . import views


app_name = "favorite"


urlpatterns = [
    # Favorites page url
    path('', views.UserFavoritesView.as_view(), name="favorites"),
    # Music favorite (add&remove) url
    path('music-favorite/<slug:slug>/', views.UserMusicFavoriteView.as_view(), name="user_music_faver"),
    # Albume favorite (add&remove) url
    path('albume-favorite/<slug:slug>/', views.UserAlbumeFavoriteView.as_view(), name="user_albume_faver"),
]

genres/urls.py
from django.urls import path
from . import views


app_name = "genres"


urlpatterns = [
    # Genre Url
    path('list/', views.GenresView.as_view(), name="genres"),
    path('<slug:slug>/', views.GenreDetail.as_view(), name="genre_detail"),
]

home/urls.py
from django.urls import path
from . import views


app_name = "home"


urlpatterns = [
    path('', views.Home.as_view(), name="home")
]

musices/urls.py
from django.urls import path
from . import views


app_name = "musices"


urlpatterns = [
    # Musices urls
    path('list/', views.MusicesView.as_view(), name="musices_list"),
    path('<slug:slug>/', views.MusicDetail.as_view(), name="music_detail"),
    path('reply-comment/<slug:slug>/<int:pk>/', views.MusicCommentReply.as_view(), name="music_comment_reply"),
]

favorites/models.py
from django.db import models
from users.models import User

    



class UserMusicFavorite(models.Model):
    
    user = models.ForeignKey(
        User,
        verbose_name="کاربر",
        on_delete=models.CASCADE,
        related_name="musices_faver"
    )
    
    music = models.ForeignKey(
        'musices.Music',
        verbose_name="آهنگ",
        on_delete=models.CASCADE,
        related_name="music_faver"
    )
    
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['created']
        verbose_name = "موزیک"
        verbose_name_plural = "موزیک ها"
        
    
    def __str__(self):
        return f'{self.music.title}'



class UserAlbumFavorite(models.Model):
    
    user = models.ForeignKey(
        User,
        verbose_name="کاربر",
        on_delete=models.CASCADE,
        related_name="albums_faver"
    )
    
    albume = models.ForeignKey(
        'alboms.Albom',
        verbose_name="آلبوم",
        on_delete=models.CASCADE,
        related_name="albome_faver"
    )
    
    created = models.DateTimeField(auto_now_add=True)
    
    
    class Meta:
        ordering = ['created']
        verbose_name = "آلبوم"
        verbose_name_plural = "آلبوم ها"
        
    
    def __str__(self):
        return f'{self.user}'

favorites/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.views import View

from .models import UserMusicFavorite, UserAlbumFavorite

from musices.models import Music
from alboms.models import Albom
from subscription.models import UserSubscription


class UserFavoritesView(View):
    
    def get(self, request):
        
        if request.user.is_authenticated == True:
            try:
                user_sub = UserSubscription.objects.get(user=request.user)
                
                user_sub.validate_subscription()
                
                if user_sub.is_active == True:
                    
                    user_musices_faver = UserMusicFavorite.objects.filter(user=request.user).order_by('-created')
                    
                    user_albums_faver = UserAlbumFavorite.objects.filter(user=request.user).order_by('-created')
                    
                    return render(
                        request, 'favorites/favorites.html', {
                            'user_musices_faver' : user_musices_faver,
                            'user_albums_faver' : user_albums_faver
                        }
                    )
                else:
                    return redirect('subscription:plans')
            except:
                return redirect('subscription:plans')
        else:
            return redirect('authentication:login')
            
        

class UserMusicFavoriteView(View):
    
    def get(self, request, slug):
        
        if request.user.is_authenticated == True:
            
            try:
                
                user_sub = UserSubscription.objects.get(user=request.user)
                
                user_sub.validate_subscription()
                
                if user_sub.is_active == True:
                    
                    music = get_object_or_404(
                        Music, 
                        slug = slug
                    )
                    
                    try:
                        
                        faver = UserMusicFavorite.objects.get(
                            user = request.user,
                            music = music
                        )
                        
                        faver.delete()
                        
                        music.likes -= 1
                        music.save()
                        
                        next_page = request.GET.get('next')
                        if next_page is not None:
                            return redirect(next_page)
                        
                        return redirect('favorites:favorites')
                    except:
                        
                        faver = UserMusicFavorite.objects.create(
                            user = request.user,
                            music = music
                        )
                        
                        faver.save
                        
                        music.likes += 1
                        music.save()
                        
                        next_page = request.GET.get('next')
                        if next_page is not None:
                            return redirect(next_page)
                        
                        return redirect('favorites:favorites')   
                else:
                    return redirect('subscription:plans')
            except:
                return redirect('subscription:plans')
        else:
            return redirect('authentication:login')
            
        

class UserAlbumeFavoriteView(View):
    
    def get(self, request, slug):
        
        if request.user.is_authenticated == True:
            
            try:
                user_sub = UserSubscription.objects.get(user=request.user)
                
                user_sub.validate_subscription()
                
                if user_sub.is_active == True:
                    
                    albume = get_object_or_404(
                        Albom, 
                        slug = slug
                    )
            
                try:
                    
                    faver = UserAlbumFavorite.objects.get(
                        user = request.user,
                        albume = albume
                    )
                    
                    faver.delete()
                    
                    albume.likes -= 1
                    albume.save()
                    
                    next_page = request.GET.get('next')
                    if next_page is not None:
                        return redirect(next_page)
                    
                    return redirect('favorites:favorites')
                except:
                    
                    faver = UserAlbumFavorite.objects.create(
                        user = request.user,
                        albume = albume
                    )
                    
                    faver.save
                    
                    albume.likes += 1
                    albume.save()
                    
                    next_page = request.GET.get('next')
                    if next_page is not None:
                        return redirect(next_page)
                    
                    return redirect('favorites:favorites')
                else:
                    return redirect('subscription:plans')
            except:
                return redirect('subscription:plans')
        else:
            return redirect('authentication:login')

favorites/templates/favorites/favorites.html
{% extends "base.html" %}
{% load static %}
{% load faver_validator %}
{% load faver_albume_validator %}

{% block title %}علاقمندی ها | Hip Hop Tweety{% endblock title %}

{% block description %}{% endblock description %}

{% block sidebar %}
<aside id="sidebar">
  <div
    class="sidebar-head d-flex align-items-center justify-content-between"
  >
    <a href="{% url "home:home" %}" class="brand external"
      ><img src="{% static "images/logos/logo.svg" %}" alt="Listen app" /> </a
    ><a
      href="javascript:void(0);"
      role="button"
      class="sidebar-toggler"
      aria-label="Sidebar toggler"
      ><div class="d-none d-lg-block">
        <i class="ri-menu-3-line sidebar-menu-1"></i>
        <i class="ri-menu-line sidebar-menu-2"></i>
      </div>
      <i class="ri-menu-fold-line d-lg-none"></i
    ></a>
  </div>
  <div class="sidebar-body" data-scroll="true">
    <nav class="navbar d-block p-0">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url "home:home" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-home-4-line fs-5"></i>
            <span class="ps-3">خانه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">دسته بندی</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a href="{% url "genres:genres" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-disc-line fs-5"></i>
            <span class="ps-3">سبک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a
            href="{% url "musices:musices_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-music-2-line fs-5"></i>
            <span class="ps-3">موزیک ها</span></a
          >
        </li>
        <li class="nav-item">
          <a href="{% url "albomes:albomes_list" %}" class="nav-link d-flex align-items-center"
            ><i class="ri-album-line fs-5"></i>
            <span class="ps-3">آلبوم ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">علاقمندی ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "favorites:favorites" %}"
            class="nav-link d-flex align-items-center active"
            ><i class="ri-heart-line fs-5"></i>
            <span class="ps-3">مورد علاقه</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">اشتراک</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "subscription:plans" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-vip-crown-line fs-5"></i>
            <span class="ps-3">پلن ها</span></a
          >
        </li>
        <li class="nav-item nav-item--head">
          <span class="nav-item--head__text">رویداد ها</span>
          <span class="nav-item--head__dots">...</span>
        </li>
        <li class="nav-item">
          <a
            href="{% url "events:events_list" %}"
            class="nav-link d-flex align-items-center"
            ><i class="ri-calendar-event-line fs-5"></i>
            <span class="ps-3">رویداد ها</span></a
          >
        </li>
      </ul>
    </nav>
  </div>
</aside>
{% endblock sidebar %}


{% block main %}
    <div class="hero"></div>
    <div class="under-hero container">
      <div class="section">
        <div class="section__head"><h3 class="mb-0">موزیک ها</h3></div>
        <div class="list list--order">
          <div class="row">
            <div class="col-xl-12">
              {% comment %} Favorites musices list {% endcomment %}
              {% for music in user_musices_faver %}
                <div
                  class="list__item"
                  data-song-id="{{ music.music.id }}"
                  data-song-name="{{ music.music.title }}"
                  data-song-artist="{{ music.music.artist }}"
                  data-song-album="{{ music.music.title }}"
                  data-song-url="{{ music.music.music_file.url}}"
                  data-song-cover="{{ music.music.image.url }}"
                >
                  <div class="list__cover">
                    <img src="{{ music.music.image.url }}" alt="{{ music.music.title }}" />
                    <a
                      href="javascript:void(0);"
                      class="btn btn-play btn-sm btn-default btn-icon rounded-pill"
                      data-play-id="{{ music.music.id }}"
                      aria-label="Play pause"
                      ><i class="ri-play-fill icon-play"></i>
                      <i class="ri-pause-fill icon-pause"></i
                    ></a>
                  </div>
                  <div class="list__content">
                    <a
                      href="{{ music.get_absolute_url }}"
                      class="list__title text-truncate"
                      >{{ music.music.title }}</a
                    >
                    <p class="list__subtitle text-truncate">
                      {{ music.music.artist }}
                    </p>
                  </div>
                  <ul class="list__option">
                    {% faver_validator user_id=user.id music_id=music.music.id as is_faver %}
                        {% if is_faver %}
                          <li>
                            <a
                              href="{% url "favorites:user_music_faver" music.music.slug %}?next=favorites:favorites"
                              role="button"
                              class="d-inline-flex active"
                              aria-label="Favorite"
                              data-favorite-id="{{  music.music.id }}"
                              ><i class="ri-heart-line heart-empty"></i>
                              <i class="ri-heart-fill heart-fill"></i>
                            </a>
                          </li>
                        {% else %}
                          <li>
                              <a
                              href="{% url "favorites:user_music_faver" music.music.slug %}?next=favorites:favorites"
                              role="button"
                              class="d-inline-flex"
                              aria-label="Favorite"
                              data-favorite-id="{{ music.music.id }}"
                              >
                                  <i class="ri-heart-line heart-empty"></i>
                                  <i class="ri-heart-fill heart-fill"></i>
                              </a>
                          </li>
                        {% endif %}
                    <li>{{ music.music.music_time }}</li>
                    <li class="dropstart d-inline-flex">
                      <a
                        class="dropdown-link"
                        href="javascript:void(0);"
                        role="button"
                        data-bs-toggle="dropdown"
                        aria-label="Cover options"
                        aria-expanded="false"
                        ><i class="ri-more-fill"></i
                      ></a>
                      <ul class="dropdown-menu dropdown-menu-sm">
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-queue-id="{{ music.music.id }}"
                            >افزودن به لیست</a
                          >
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-next-id="{{ music.music.id }}"
                            >بعدی برای پخش</a
                          >
                        </li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            >اشتراک</a
                          >
                        </li>
                        <li class="dropdown-divider"></li>
                        <li>
                          <a
                            class="dropdown-item"
                            href="javascript:void(0);"
                            role="button"
                            data-play-id="{{ music.music.id }}"
                            >پخش</a
                          >
                        </li>
                      </ul>
                    </li>
                  </ul>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <div class="section">
        <div class="section__head"><h3 class="mb-0">آلبوم ها</h3></div>
        <div class="row g-4">
          {% comment %} Album favorites {% endcomment %}
          {% for albume in user_albums_faver %}
            <div class="col-6 col-xl-2 col-md-3 col-sm-4">
              <div class="cover cover--round">
                <div class="cover__head">
                  <ul class="cover__label d-flex">
                    {% faver_albume_validator user_id=user.id albume_id=albume.albume.id as is_albume_faver %}
                    {% if is_albume_faver %}
                      <li>
                        <a
                          href="{% url "favorites:user_albume_faver" albume.albume.slug %}?next=favorites:favorites"
                          role="button"
                          class="d-inline-flex active"
                          aria-label="Favorite"
                          data-favorite-id="{{ albume.albume.id }}"
                          ><i class="ri-heart-line heart-empty"></i>
                          <i class="ri-heart-fill heart-fill"></i>
                        </a>
                      </li>
                    {% else %}
                      <li>
                          <a
                          href="{% url "favorites:user_albume_faver" albume.albume.slug %}?next=favorites:favorites"
                          role="button"
                          class="d-inline-flex"
                          aria-label="Favorite"
                          data-favorite-id="{{ albume.albume.id }}"
                          >
                              <i class="ri-heart-line heart-empty"></i>
                              <i class="ri-heart-fill heart-fill"></i>
                          </a>
                      </li>
                    {% endif %}
                  </ul>
                  <div class="cover__options dropstart d-inline-flex ms-auto">
                    <a
                      class="dropdown-link"
                      href="javascript:void(0);"
                      role="button"
                      data-bs-toggle="dropdown"
                      aria-label="Cover options"
                      aria-expanded="false"
                      ><i class="ri-more-2-fill"></i
                    ></a>
                    <ul class="dropdown-menu dropdown-menu-sm">
                      <li>
                        <a
                          class="dropdown-item"
                          href="javascript:void(0);"
                          role="button"
                          >اشتراک</a
                        >
                      </li>
                      <li class="dropdown-divider"></li>
                      <li>
                        <a class="dropdown-item" href="{{ albume.albume.get_absolute_url }}"
                          >نمایش جزئیات</a
                        >
                      </li>
                    </ul>
                  </div>
                </div>
                <a href="{{ album.get_absolute_url }}" class="cover__image"
                  ><img src="{{ albume.albume.image.url }}" alt="{{ albume.albume.title }}"
                /></a>
                <div class="cover__foot">
                  <a
                    href="{{ albume.albume.get_absolute_url }}"
                    class="cover__title text-truncate"
                    >{{ albume.albume.title }}</a
                  >
                  <p class="cover__subtitle text-truncate">
                    {{ albume.albume.singer }}
                  </p>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
{% endblock main %}